services:
  py-utils:
    image: 'adtsw/prod:algostonk-py-utils-arm64'
    container_name: py-utils
    environment:
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - '/data:/data'
    ports:
      - "17434:8080"
    command:
      - bash
    tty: true
    stdin_open: true
    restart: "no"
