services:
  py-utils:
    image: 'adtsw/prod:algostonk-py-utils-arm64'
    container_name: py-utils
    environment:
      AWS_BUCKET_NAME: '${AWS_BUCKET_NAME}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    volumes:
      - '/data:/data'
    ports:
      - '17434:17434'
    command:
      - bash
    tty: true
    stdin_open: true
    restart: 'no'
    labels:
      - caddy_0.basicauth.0_adtsw=$2a$14$tUxIwsUTdC4mGJunw1OJ3ukG3uLsFrjqVbAy8JQtAiOtgvO8T.MRy
